#ifndef _INCLUDE_JS8_JSC_H_
#define _INCLUDE_JS8_JSC_H_

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* JS8 free-text decoding (J7).
 *
 * A JS8 data frame is [1][1][70]: one bit saying this is data, one choosing
 * the coding, and seventy bits of payload. Two codings:
 *
 *   [10x]  per-character Huffman over a 44-entry alphabet
 *   [11x]  JSC word coding - (s,c)-dense indices into a word list
 *
 * JS8Call picks per frame, whichever packs MORE characters, so a real
 * transmission mixes them and both have to work.
 *
 * ⛔ THE TABLES ARE JS8CALL'S, under GPL-3, and that is why this project is
 * GPL-3 (relicensed from MIT on 2026-10-09). They are generated by
 * tools/gen_js8_jsc_tables.py and must be regenerated, never edited: a wrong
 * entry reads exactly like a decoder bug.
 *
 * ⚠ THE WORD LIST IS TRUNCATED at kJS8_JSC_words - every index reachable in
 * 20 bits or fewer. The full 262144 entries are 2893 KB against ~2.4 MB of
 * free app partition, so it does not fit regardless of licence. An index at
 * or above the cut renders as JS8_JSC_UNKNOWN_WORD rather than being dropped
 * or guessed, so a line with one rare word in it is still readable. */

#define JS8_JSC_UNKNOWN_WORD  "<?>"

/* The longest text a 70-bit frame can hold. 70 bits of Huffman at the
 * shortest code (2 bits for a space) is 35 characters; the word coding can
 * reach 14 short words. 96 is comfortably above both and keeps the struct off
 * the edge of a guess. */
#define JS8_JSC_TEXT_MAX      96

/* ---- the generated tables (js8_jsc_tables.c) ------------------------- */

typedef struct {
    const char* ch;     /* one character, as a C string */
    const char* code;   /* its bits, as '0'/'1' characters */
} js8_huff_entry_t;

extern const uint32_t kJS8_JSC_words;
extern const uint32_t kJS8_JSC_stride;
extern const uint32_t kJS8_JSC_blob_len;
extern const uint32_t kJS8_JSC_index[];
extern const char     kJS8_JSC_blob[];
extern const js8_huff_entry_t kJS8_Huff[];
extern const uint32_t kJS8_Huff_count;

/* Word at `index`, or NULL at or above the truncation point. Points into the
 * blob; never freed, never modified. */
const char* js8_jsc_word(uint32_t index);

/* ---- decoding -------------------------------------------------------- */

/* Decode the 70 payload bits of a data frame.
 *
 * `bits` holds one bit per byte (0 or 1), `n_bits` of them, ALREADY stripped
 * of the two flag bits and of the trailing pad. js8_jsc_unpad() does that
 * stripping; keeping them separate is deliberate, because the padding rule is
 * shared by both codings and the test vectors are easier to state without it.
 *
 * Returns the number of characters written, or -1. */
int js8_jsc_decode_huff(const uint8_t* bits, int n_bits,
                        char* out, size_t out_len);
int js8_jsc_decode_words(const uint8_t* bits, int n_bits,
                         char* out, size_t out_len);

/* The padding convention: after the content comes a single 0 and then all 1s.
 * To unpad, seek back from the end to the last 0 and drop it and everything
 * after. Returns the content length in bits, or -1 if there is no 0 at all
 * (which means the frame is not a padded frame and must not be decoded).
 *
 * ⭐ THERE IS ALWAYS A PAD BIT, which is what makes this safe. The encoder's
 * fill loop stops while `length + charBits < frameSize` STRICTLY, so the
 * content can never reach the full width and at least one 0 always follows
 * it. An earlier version of this comment claimed the opposite - that a full
 * frame might have no pad - which would have made seeking back to the last 0
 * capable of eating a content bit. It cannot. */
int js8_jsc_unpad(const uint8_t* bits, int n_bits);

/* The whole job: a 9-byte frame in, text out. Reads the two flag bits to
 * choose the coding, unpads, and decodes. Returns false if the frame is not a
 * data frame or if nothing could be read from it. */
bool js8_jsc_frame_to_text(const uint8_t frame[9], char* out, size_t out_len);

/* ---- encoding (J8), in js8_jsc_encode.c ------------------------------- */

/* Fold `in` into what JS8 can actually carry: upper case, runs of whitespace
 * collapsed to one space, leading/trailing space removed, and any character
 * with no Huffman code dropped. Returns the length written, or -1.
 *
 * Call this before showing the operator a frame count - what they typed and
 * what will be sent are not the same string, and the count belongs to the
 * second one. */
int js8_jsc_normalize(const char* in, char* out, size_t out_len);

/* Encode as much of `text` as fits into ONE frame. Returns the number of
 * CHARACTERS consumed (so the caller can advance), or -1.
 *
 * Both codings are tried and the one that carries more characters wins, which
 * is what the reference encoder does and why a real transmission mixes them.
 * `text` should already be normalised. */
int js8_jsc_text_to_frame(const char* text, uint8_t frame[9]);

/* Encode a whole message into consecutive frames. `frames` is `max_frames` x 9
 * bytes. Returns the number of frames written.
 *
 * ⛔ THE itypes ARE NOT OPTIONAL. They carry JS8_ITYPE_FIRST / _LAST, which is
 * how the receiving station knows where the message begins and ends; sending
 * every frame as 0 marks them all as MIDDLE frames and the far end waits for
 * an end that never comes. See the note at JS8_ITYPE_* in js8_message.h.
 *
 * ⚠ EACH FRAME IS ONE SLOT. A three-frame message is 45 seconds of
 * transmission in JS8 Normal, and the operator must be told that BEFORE the
 * radio is keyed, not after. */
int js8_jsc_text_to_frames(const char* text, uint8_t* frames, uint8_t* itypes,
                           int max_frames);

#ifdef __cplusplus
}
#endif

#endif /* _INCLUDE_JS8_JSC_H_ */
