/* Host test for the JS8 Normal codec core (J1 of docs/js8-feasibility.md):
 * the (174,87) LDPC tables, the colorder permutation, CRC-12, and the
 * payload bit layout.
 *
 * Build (from the repo root):
 *   gcc -O2 -Wall -I components/ft8_lib -I components/ft8_lib/ft8 \
 *       -o js8_codec_harness test/js8_codec_harness.c \
 *       components/ft8_lib/ft8/js8_codec.c components/ft8_lib/ft8/js8_tables.c \
 *       components/ft8_lib/ft8/ldpc.c components/ft8_lib/ft8/constants.c \
 *       -lm && ./js8_codec_harness
 *
 * WHY. The feasibility note ranks LDPC table transcription as risk #1, for a
 * specific reason: a wrong parity table is indistinguishable from a wrong
 * Costas array or a wrong bit order, because all three produce exactly one
 * symptom - nothing ever decodes. On the air that costs a session to find.
 * Here it costs a second.
 *
 * The tables are machine-generated by tools/gen_js8_ldpc_tables.py from
 * JS8Call 2.3.1 (tag v2.3.1, fd721e8b67ee), so nobody retypes them. This
 * harness then checks five independent things:
 *
 *  1. CRC ENGINE against a catalogued CRC. js8_crc12_raw() with polynomial
 *     0x80F over "123456789" plus 12 zero bits must give 0xF5B, the published
 *     check value of CRC-12/DECT. JS8's own polynomial (0xC06) is not in any
 *     CRC catalogue, so this proves the division loop is a correct CRC before
 *     the JS8 polynomial is trusted on top of it.
 *
 *  2. ENCODER against JS8Call's own Fortran. kRefCw[] was produced by
 *     compiling lib/ft8/encode174.f90 + lib/ft8/ldpc_174_87_params.f90
 *     unmodified with gfortran and feeding them the messages in kRefMsg[]
 *     (deterministic LCG driver). This is the arbiter for the generator
 *     matrix AND the colorder permutation together.
 *
 *  3. GENERATOR against PARITY MATRIX. The generator comes from
 *     ldpc_174_87_params.f90; Nm/Mn come from bpdecode174.f90 - two separate
 *     files. Every encoded codeword must satisfy all 87 checks. If either
 *     table were misparsed, this fails. It is a cross-check, not a
 *     comparison of the code against itself.
 *
 *  4. ROUND TRIP through bp_decode_code(), the engine FT8 uses, with the JS8
 *     code passed in - clean, then with bit errors injected - and the payload
 *     recovered through the inverse colorder with its CRC-12 verified.
 *
 *  5. PAYLOAD LAYOUT: frame(72) + itype(3) + crc(12), in that order. The
 *     feasibility note had itype FIRST; genjs8.f90 puts it after the frame.
 *
 * WHAT THIS DOES NOT PROVE. The CRC-12 POLYNOMIAL, the XOR-42 and the 13-bit
 * zero tail are transcribed from lib/crc12.cpp and genjs8.f90 and are only
 * checked here for self-consistency - pack, then check. Boost is not on this
 * machine, so augmented_crc was reimplemented rather than linked. Only a real
 * JS8Call station decoding our frame settles it. Do NOT settle it with a
 * second Tab5: two copies of this implementation share their mistakes.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "js8.h"
#include "ldpc.h"

static int g_fail = 0;

static void check(int ok, const char* what)
{
    printf("  %-58s %s\n", what, ok ? "ok" : "FAIL");
    if (!ok)
        g_fail++;
}

static const char* kRefMsg[8] = {
    "110001010000011001110110011000101101000100010100011110010100001110101001011010011000110",
    "000001111100101001101111100100010000111100011000000000001110001011100011010111011011010",
    "101011000010000000100011000110010110100100001100001011111110101011010010110000001110111",
    "100010110010111011110110100010001010111101010100000110111010101111011000010100111000100",
    "010010111000110101011011101000101011010110011001110000111101101000101011010010100011000",
    "111110110101000011011110001101100011011111000111110101111110010110110011100011000110001",
    "101111001010100111001011011010101011100100010110011011000101100100001000111100110000011",
    "010110001001100000111101000110001001001111101001000100010101000100001001110100111000111",
};

static const char* kRefCw[8] = {
    "110100101011010100010000010011110010001110001010110000100100000110000001101101110011010110001010000011001110110011000101101000100010100011110010100001110101001011010011000110",
    "101011001110110101011101100011100111010111000101001010110010010100101010001010101011110000001111100101001101111100100010000111100011000000000001110001011100011010111011011010",
    "001100111111010101001000000000011100000010011000000001011000010000001001100010011001101101011000010000000100011000110010110100100001100001011111110101011010010110000001110111",
    "011011110101011110110010111010101010100011011110010001001110010100010010111011011101100100010110010111011110110100010001010111101010100000110111010101111011000010100111000100",
    "011111001001010100000101001011101100001111111101100001111010111011011001011010100010110010010111000110101011011101000101011010110011001110000111101101000101011010010100011000",
    "000000011000011010010111000101001110001100111110000000001111111011011110001011111100101111110110101000011011110001101100011011111000111110101111110010110110011100011000110001",
    "000001000011000111001000001101010010010011000011010001011101001001101001101101100111100101111001010100111001011011010101011100100010110011011000101100100001000111100110000011",
    "100001111000110010110000100010111011010011100000110011110011010000000101010101011110001010110001001100000111101000110001001001111101001000100010101000100001001110100111000111",
};

#define NREF ((int)(sizeof(kRefMsg) / sizeof(kRefMsg[0])))

static void bits_from_text(const char* s, uint8_t* out, int n)
{
    for (int i = 0; i < n; ++i)
        out[i] = (uint8_t)(s[i] == '1');
}

/* ---- 1. CRC engine against a catalogued CRC ---------------------------- */

static void test_crc_engine(void)
{
    /* CRC-12/DECT: poly 0x80F, init 0, no reflection, no final XOR, and the
     * published check value for "123456789" is 0xF5B. The augmenting zeros
     * are supplied here, because js8_crc12_raw() does not add them. */
    uint8_t buf[11];
    memset(buf, 0, sizeof(buf));
    memcpy(buf, "123456789", 9);
    uint16_t crc = js8_crc12_raw(buf, 9 * 8 + 12, 0x80Fu);
    printf("  CRC-12/DECT of the standard check string = 0x%03X, expected 0xF5B\n", crc);
    check(crc == 0xF5Bu, "CRC division loop matches a catalogued CRC-12");
}

/* ---- 2. Encoder against JS8Call's Fortran ------------------------------ */

static void test_encode_against_fortran(void)
{
    int bad = 0;
    for (int v = 0; v < NREF; ++v)
    {
        uint8_t msg[JS8_LDPC_K], cw[JS8_LDPC_N], ref[JS8_LDPC_N];
        bits_from_text(kRefMsg[v], msg, JS8_LDPC_K);
        bits_from_text(kRefCw[v], ref, JS8_LDPC_N);
        js8_encode174(msg, cw);
        if (memcmp(cw, ref, JS8_LDPC_N) != 0)
        {
            bad++;
            printf("    vector %d differs\n", v);
        }
    }
    printf("  %d of %d reference codewords reproduced\n", NREF - bad, NREF);
    check(bad == 0, "js8_encode174 matches JS8Call encode174.f90");
}

/* ---- 3. Generator against the parity-check matrix ---------------------- */

static int parity_errors(const uint8_t cw[JS8_LDPC_N])
{
    const ftx_ldpc_code_t* c = &kJS8_LDPC_code_174_87;
    int errors = 0;
    for (int m = 0; m < c->M; ++m)
    {
        uint8_t x = 0;
        for (int i = 0; i < c->Num_rows[m]; ++i)
            x ^= cw[c->Nm[m][i] - 1];
        if (x)
            errors++;
    }
    return errors;
}

static void test_generator_vs_parity(void)
{
    int bad = 0;
    unsigned seed = 1;
    for (int t = 0; t < 200; ++t)
    {
        uint8_t msg[JS8_LDPC_K], cw[JS8_LDPC_N];
        for (int i = 0; i < JS8_LDPC_K; ++i)
        {
            seed = seed * 1103515245u + 12345u;
            msg[i] = (uint8_t)((seed >> 16) & 1u);
        }
        js8_encode174(msg, cw);
        if (parity_errors(cw) != 0)
            bad++;
    }
    printf("  %d of 200 random codewords satisfy all 87 checks\n", 200 - bad);
    check(bad == 0, "generator and parity matrix agree (separate source files)");
}

/* ---- 4. Round trip through the shared belief-propagation engine -------- */

static void to_llr(const uint8_t cw[JS8_LDPC_N], float llr[JS8_LDPC_N], float amp)
{
    /* ldpc.c's header comment says the input is the log-likelihood of ZERO,
     * but the code does plain[n] = (llr > 0) ? 1 : 0 - so a POSITIVE value
     * means a 1 bit. The comment is wrong; the hard decision is the
     * authority, and it is what decode.c feeds. */
    for (int i = 0; i < JS8_LDPC_N; ++i)
        llr[i] = cw[i] ? amp : -amp;
}

static void test_round_trip(void)
{
    unsigned seed = 7;
    int clean_ok = 0, noisy_ok = 0;
    const int trials = 100;

    for (int t = 0; t < trials; ++t)
    {
        uint8_t frame[9];
        for (int i = 0; i < 9; ++i)
        {
            seed = seed * 1103515245u + 12345u;
            frame[i] = (uint8_t)(seed >> 16);
        }
        uint8_t itype = (uint8_t)(t & 7);

        uint8_t payload[JS8_LDPC_K], cw[JS8_LDPC_N];
        js8_pack_payload(frame, itype, payload);
        js8_encode174(payload, cw);

        float llr[JS8_LDPC_N];
        uint8_t plain[JS8_LDPC_N];
        int errs = 0;

        to_llr(cw, llr, 4.0f);
        bp_decode_code(&kJS8_LDPC_code_174_87, llr, 30, 0, plain, &errs);
        if (errs == 0 && memcmp(plain, cw, JS8_LDPC_N) == 0)
        {
            /* Undo colorder: the payload is the last 87 bits of the
             * un-permuted codeword (encode174.f90's itmp(M+1:N)=message). */
            uint8_t itmp[JS8_LDPC_N], got[JS8_LDPC_K];
            for (int i = 0; i < JS8_LDPC_N; ++i)
                itmp[i] = plain[kJS8_LDPC_colorder[i]];
            memcpy(got, itmp + JS8_LDPC_M, JS8_LDPC_K);
            if (memcmp(got, payload, JS8_LDPC_K) == 0 && js8_check_payload_crc(got))
                clean_ok++;
        }

        /* The same codeword with 8 bits flipped - well inside what a (174,87)
         * rate-1/2 code should carry, and it exercises the iteration path
         * rather than the iteration-0 shortcut. */
        uint8_t noisy[JS8_LDPC_N];
        memcpy(noisy, cw, JS8_LDPC_N);
        for (int k = 0; k < 8; ++k)
        {
            seed = seed * 1103515245u + 12345u;
            int pos = (int)((seed >> 16) % JS8_LDPC_N);
            noisy[pos] ^= 1u;
        }
        to_llr(noisy, llr, 2.0f);
        bp_decode_code(&kJS8_LDPC_code_174_87, llr, 30, 0, plain, &errs);
        if (errs == 0 && memcmp(plain, cw, JS8_LDPC_N) == 0)
            noisy_ok++;
    }

    printf("  clean round trips %d/%d, 8-bit-error corrections %d/%d\n",
           clean_ok, trials, noisy_ok, trials);
    check(clean_ok == trials, "encode -> bp_decode_code -> payload + CRC round trip");
    check(noisy_ok >= trials * 9 / 10, "8 flipped bits corrected in 90% of trials or more");
}

/* ---- 5. Payload layout ------------------------------------------------- */

static void test_payload_layout(void)
{
    uint8_t frame[9] = { 0xDE, 0xAD, 0xBE, 0xEF, 0x01, 0x23, 0x45, 0x67, 0x89 };
    uint8_t payload[JS8_LDPC_K];
    js8_pack_payload(frame, 3, payload);

    int ok = 1;
    for (int i = 0; i < JS8_FRAME_BITS; ++i)
        if (payload[i] != ((frame[i / 8] >> (7 - (i % 8))) & 1u))
            ok = 0;
    /* itype 3 = 0b011, written after the frame, not before it. */
    ok = ok && payload[72] == 0 && payload[73] == 1 && payload[74] == 1;
    check(ok, "payload is frame(72) + itype(3) + crc(12), in that order");
    check(js8_check_payload_crc(payload), "carried CRC-12 verifies");

    payload[5] ^= 1u;
    check(!js8_check_payload_crc(payload), "a flipped message bit fails the CRC");
}

int main(void)
{
    printf("JS8 Normal codec core\n");
    test_crc_engine();
    test_encode_against_fortran();
    test_generator_vs_parity();
    test_round_trip();
    test_payload_layout();

    if (g_fail)
    {
        printf("\nFAILED: %d check(s)\n", g_fail);
        return 1;
    }
    printf("\nall checks passed\n");
    return 0;
}
