idf_component_register(
    SRCS
        "main.c"
        "display/display.c"
        "ui/ui.c"
        "ui/wifi_config.c"
        "util/status.c"
        "util/battery.c"
        "util/ina226.c"
        "util/bsp_info.c"
        "cat/cat.c"
        "audio/audio.c"
        "dsp/dsp.c"
        "dsp/iq_balance.c"
        "render/render.c"
        "render/render_waterfall.c"
        "screenshot/screenshot.c"
        "storage/settings.c"
        "wifi/wifi.c"
        "net/webserver.c"
        "net/webserver_ws.c"
        "net/rigctld_server.c"
    INCLUDE_DIRS
        "."
        "display"
        "ui"
        "util"
        "cat"
        "audio"
        "dsp"
        "render"
        "screenshot"
        "storage"
        "wifi"
        "net"
    REQUIRES
        esp_lcd
        esp_timer
        driver
        usb
        lvgl__lvgl
        m5stack_tab5
        espressif__esp_lcd_touch
        espressif__usb_host_cdc_acm
        espressif__usb_host_uac
        espressif__esp-dsp
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        lwip
        esp_http_server
        json
    PRIV_REQUIRES
        esp_app_format
    EMBED_TXTFILES
        "net/www/index.html"
)