idf_component_register(
    SRCS
        "main.c"
        "display/display.c"
        "ui/ui.c"
        "util/fps.c"
        "cat/cat.c"
        "audio/audio.c"
        "dsp/dsp.c"
        "render/render.c"
    INCLUDE_DIRS
        "."
        "display"
        "ui"
        "util"
        "cat"
        "audio"
        "dsp"
        "render"
    REQUIRES
        esp_lcd
        esp_timer
        driver
        usb
        lvgl__lvgl
        m5stack_tab5
        espressif__esp_lcd_touch
        espressif__usb_host_cdc_acm
        espressif__usb_host_uac
        espressif__esp-dsp
)
