#!/usr/bin/env python3
"""Emit the JS8 (174,87) LDPC tables as C, straight from JS8Call's Fortran.

The tables are NOT hand-transcribed, deliberately: a transcription error in a
parity-check matrix is indistinguishable from a sync or Costas bug - both read
as "never decodes". This parses the source files instead, so the only thing a
human writes is the path to them.

Inputs (JS8Call 2.3.1, tag v2.3.1 = fd721e8b67ee):
  lib/ft8/ldpc_174_87_params.f90   generator matrix g(87), colorder(174)
  lib/ft8/bpdecode174.f90          Nm(7,87), Mn(3,174), nrw(87)

Usage:
  python tools/gen_js8_ldpc_tables.py <params.f90> <bpdecode174.f90> > out.c
"""
import re
import sys


def read(path):
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        return f.read()


def data_block(src, name):
    """Return the text of a Fortran `data <name>/ ... /` block."""
    m = re.search(r'data\s+' + name + r'\s*/(.*?)/\s*\n', src, re.S | re.I)
    if not m:
        raise SystemExit('no data block for %s' % name)
    return m.group(1)


def ints(block):
    """Every integer in a data block, continuations and comments removed."""
    txt = re.sub(r'!.*', '', block)
    txt = txt.replace('&', ' ')
    return [int(x) for x in re.findall(r'-?\d+', txt)]


def hexstrings(block):
    return re.findall(r'"([0-9a-fA-F]+)"', block)


def emit(name, rows, width, per_line=16):
    print('const uint8_t %s[%d][%d] = {' % (name, len(rows), width))
    for r in rows:
        print('    { %s },' % ', '.join('%3d' % v for v in r))
    print('};')
    print()


def main():
    params = read(sys.argv[1])
    bp = read(sys.argv[2])

    g = hexstrings(data_block(params, 'g'))
    if len(g) != 87:
        raise SystemExit('expected 87 generator rows, got %d' % len(g))
    gen = []
    for row in g:
        if len(row) != 22:
            raise SystemExit('generator row is %d hex chars, expected 22' % len(row))
        b = [int(row[i:i + 2], 16) for i in range(0, 22, 2)]
        # Bits 88..88 of the 11 bytes are padding past K=87 and must be zero,
        # or the encoder would fold a stray bit into every parity sum.
        if b[10] & 0x01:
            raise SystemExit('generator row has a set bit past K=87: %s' % row)
        gen.append(b)

    colorder = ints(data_block(params, 'colorder'))
    if len(colorder) != 174:
        raise SystemExit('colorder has %d entries' % len(colorder))
    if sorted(colorder) != list(range(174)):
        raise SystemExit('colorder is not a permutation of 0..173')

    nm = ints(data_block(bp, 'Nm'))
    mn = ints(data_block(bp, 'Mn'))
    nrw = ints(data_block(bp, 'nrw'))
    if len(nm) != 87 * 7 or len(mn) != 174 * 3 or len(nrw) != 87:
        raise SystemExit('Nm/Mn/nrw sizes: %d %d %d' % (len(nm), len(mn), len(nrw)))

    nm_rows = [nm[i * 7:(i + 1) * 7] for i in range(87)]
    mn_rows = [mn[i * 3:(i + 1) * 3] for i in range(174)]

    # Consistency: Nm and Mn must describe the same bipartite graph, and the
    # used length of each Nm row must equal nrw. Checked here so a bad parse
    # fails loudly instead of becoming a decoder that never converges.
    for m, row in enumerate(nm_rows):
        used = [v for v in row if v != 0]
        if len(used) != nrw[m]:
            raise SystemExit('check %d: %d non-zero entries, nrw says %d'
                             % (m + 1, len(used), nrw[m]))
        if row[:nrw[m]] != used:
            raise SystemExit('check %d: zero padding is not at the end' % (m + 1))
    edges_nm = set()
    for m, row in enumerate(nm_rows):
        for n in row[:nrw[m]]:
            edges_nm.add((m + 1, n))
    edges_mn = set()
    for n, row in enumerate(mn_rows):
        for m in row:
            edges_mn.add((m, n + 1))
    if edges_nm != edges_mn:
        raise SystemExit('Nm and Mn disagree on %d edges'
                         % len(edges_nm ^ edges_mn))
    if len(edges_nm) != sum(nrw):
        raise SystemExit('duplicate edge in Nm')

    print('// Generated by tools/gen_js8_ldpc_tables.py from JS8Call 2.3.1')
    print('// (tag v2.3.1, fd721e8b67ee): lib/ft8/ldpc_174_87_params.f90 and')
    print('// lib/ft8/bpdecode174.f90. Do not hand-edit - regenerate.')
    print('//')
    print('// Fortran is 1-based and the tables keep that: Nm/Mn entries are')
    print('// 1-based bit/check indices, as FT8\'s own tables in this file are.')
    print('// colorder is 0-based, as it is in the Fortran.')
    print()
    emit('kJS8_LDPC_generator', gen, 11)
    emit('kJS8_LDPC_Nm', nm_rows, 7)
    emit('kJS8_LDPC_Mn', mn_rows, 3)
    print('const uint8_t kJS8_LDPC_Num_rows[87] = {')
    for i in range(0, 87, 16):
        print('    %s' % ', '.join(str(v) for v in nrw[i:i + 16]) + ',')
    print('};')
    print()
    print('const uint8_t kJS8_LDPC_colorder[174] = {')
    for i in range(0, 174, 16):
        print('    %s' % ', '.join('%3d' % v for v in colorder[i:i + 16]) + ',')
    print('};')
    sys.stderr.write('ok: 87 generator rows, %d edges, colorder is a permutation\n'
                     % len(edges_nm))


main()
